### ISSUE TITLE
Rails 6

### ISSUE THREAD

**Issue by Tressa-Sanders** [mattantonelli/dynamic_selectable#17]
Any plans to make this work in Rails 6? 
Right now it won't install the gem because it says it's not compatible with Rails 6.

**Comment by mattantonelli** [comment]
I haven't had a chance to try this with Rails 6 yet. If you'd like, you can try easing the runtime dependencies in the `.gemspec` and see if you can get it to work with your project.

**Comment by Tressa-Sanders** [comment]
Thanks. I didn't need it after all. I just got dynamic select menus to work pretty easily without a gem. :)

**Comment by mattantonelli** [comment]
Yeah, it's not too terrible. The gem is just a convenience thing.

**Comment by ctomsyck** [comment]
Matt,


I am not sure why I am getting your emails.  Am I on your GitHub account or
something.

**Comment by mattantonelli** [comment]
You have the repo set to Watch ;)
